function [] = plotall()
%Plotting function 
%   This function plots the following
% Tn vs Ta for each wall
% Mn vs Ma for each wall 
% Mgbn vs Mgba
% Total nodal rotation: thetan(Numerical) vs theta 

load mainvar
%Plot Parameters 
ImageFontSizeM=11;
ImageFontSize=9;
LegendFontSize=7;
MarkSize=6;
FontName='Garamond';
AxisFontName='CMU Serif';
axes1 = axes('FontSize',ImageFontSize,'FontName',AxisFontName);
box(axes1,'on');
hold(axes1,'all');
% --------------------------------------------------------------------------
%% Outputs: Plotting section frequencies
% --------------------------------------------------------------------------

figure 
plot(xE(1),yE(1),'ok',xE(2),yE(2),'xk',xE(3),yE(3),'sk',xE(4),yE(4),'dk','LineWidth',1.5,'MarkerSize',MarkSize);
hold on
xlim([-3,3]); ylim([0,5]); gx=[-3 -1 0 1]; gy=[4 2 1 0];ix=[-1 -2 -3 -4]; iy=[0 1 2 3];
plot(xlim,  [1 1], '--k', [1 1], ylim,[-1 -1], ylim, gx, gy, ix, iy)           
hold off
slegen1=legend(': Structure F1: mode 1', ': Structure F1: mode 2',': Structure F1: mode 3',': Structure F1: mode 4');
l=xlabel('$ x (C= \varepsilon^x) Bending/Shear$','FontSize',ImageFontSize,'FontName',AxisFontName); l2=ylabel('$y (\gamma= \varepsilon^y) Inner Bending/Global Bending$','FontSize',ImageFontSize,'FontName',AxisFontName);
title(' Evolution of the structural behavior  ','FontSize',ImageFontSizeM,'FontName',FontName);
set(l,'interpreter','latex');set(l2,'interpreter','latex');
set(slegen1,'FontName',AxisFontName,'FontSize',LegendFontSize);
figure 
loglog(N(1),f_natural(1),'sr',N(1),f_natural(2),'ok',N(1),f_natural(3),'dm','LineWidth',1.2,'MarkerSize',6); grid on;
hold on
xlabel('Cell number','FontSize',ImageFontSize,'FontName',AxisFontName); ylabel('Frequency [Hz]','FontSize',ImageFontSize,'FontName',AxisFontName);
slegen=legend(': Mode 1', ': Mode 2',  ': Mode 3',  ': Mode 4');
title(' Frequencies ','FontSize',ImageFontSizeM,'FontName',FontName);
set(slegen,'FontName',AxisFontName,'FontSize',LegendFontSize);
figure 
plot(Omega_graph,  deter, '-k','LineWidth',1.5); grid on; 
xlabel('\omega [rad/s]','FontSize',ImageFontSize,'FontName',AxisFontName); ylabel('Amplitude','FontSize',ImageFontSize,'FontName',AxisFontName);

for h=1:3
    md=h;
f=figure;
p = uipanel('Parent',f,'Title','Total Shear Force on each wall','TitlePosition','centertop','FontSize',ImageFontSizeM,...
            'FontWeight','bold','FontName', FontName,...
               'BackgroundColor','white',...
               'BorderType','none'); 
for i=1:nw
subplot(round(nw/2),2,i,'Parent',p)
% sForce_n(i)   = barh(Tnum{md}(1:(end-1),i),x_t(1:(end-1)));
% sForce_a(i)   = barh(T{md}(1:(end-1),i),x_t(1:(end-1)));
% sForce_cast(i)   = barh(TCastem{md}(1:(end-1),i),x_t(1:(end-1)));
Tmatrix=[Tnum{md}(1:(end-1),i) TCastem{md}(1:(end-1),i) T{md}(1:(end-1),i)];
 fig1=barh(x_t(1:(end-1)), Tmatrix);
  set (fig1(1), 'FaceColor', [.2 .2 .2]);
 set (fig1(2), 'FaceColor', [.3 .3 .3]);
 set (fig1(3), 'FaceColor', [.7 .7 .7]);

% 
% set(sForce_n(i)                         , ...
%    'FaceColor',    'b' );
% set(sForce_a(i)                         , ...
%    'FaceColor'           , 'r' );
% set(sForce_cast(i)       , ...
%    'FaceColor'           , 'g' );

hLegend = legend( 'Tn (Un,\theta n) ' , ...
  'Tn (Cast3m) ' , ...
  'Ta (Ua,\theta a) ',...
  'location', 'NorthEast' );
nws=num2str(i);
nWall=strcat('Wall Axe: ',' ',nws);
hTitle  = title (nWall);
hXLabel = xlabel('Total Shear Force (KN)'                     );
hYLabel = ylabel('x (mm)'                      );
set([hTitle, hXLabel, hYLabel], ...
    'FontName'   , FontName);
set([hXLabel, hYLabel]  , ...
    'FontSize'   , ImageFontSize          );
set( hTitle                    , ...
    'FontSize'   , ImageFontSize          , ...
    'FontWeight' , 'bold'      );
set([hLegend, gca]             , ...
    'FontSize'   , LegendFontSize           );
set( gca                       , ...
    'FontName'   , AxisFontName );
set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , 0:lw:N*lw, ...
  'LineWidth'   , 1         );
end
set(gcf, 'Position', get(0, 'Screensize'));
end



for h=1:3
    md=h;
f=figure;
p = uipanel('Parent',f,'Title','Bending Moment on each wall','TitlePosition','centertop','FontSize',ImageFontSizeM,...
            'FontWeight','bold','FontName', FontName,...
               'BackgroundColor','white',...
               'BorderType','none'); 

for i=1:nw
subplot(round(nw/2),2,i,'Parent',p)
bMom_n(i)= plot(Mnum{md}(:,i),x_t,'s');
hold on
bMom_a(i)= plot(M{md}(:,i), x_t, 'o');

set(bMom_n(i)                         , ...
  'MarkerSize'      , MarkSize           , ...
  'MarkerEdgeColor' , 'none'  , ...
  'MarkerFaceColor' , [.2 .2 .2]  );
set(bMom_a(i)                         , ...
  'MarkerSize'      , MarkSize           , ...
  'MarkerEdgeColor' , 'none' , ...
  'MarkerFaceColor' , [.7 .7 .7]  );

hLegend = legend( ...
  [bMom_n(i), bMom_a(i)], ...
  'Mn (Un,\theta n) ' , ...
  'Ma (Ua,\theta a) ' , ...
  'location', 'NorthEast' );
nws=num2str(i);
nWall=strcat('Wall Axe: ',' ',nws);
hTitle  = title (nWall);
hXLabel = xlabel('Bending Moment (KNmm)'                     );
hYLabel = ylabel('x (mm)'                      );
set([hTitle, hXLabel, hYLabel], ...
    'FontName'   , FontName);
set([hXLabel, hYLabel]  , ...
    'FontSize'   , ImageFontSize          );
set( hTitle                    , ...
    'FontSize'   , ImageFontSize          , ...
    'FontWeight' , 'bold'      );
set([hLegend, gca]             , ...
    'FontSize'   , LegendFontSize           );
set( gca                       , ...
    'FontName'   , AxisFontName );
set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , 0:lw:N*lw, ...
  'LineWidth'   , 1         );
end
set(gcf, 'Position', get(0, 'Screensize'));
end
end

