function [] = plotall()
%Plotting function 
%   This function plots the following
% Tn vs Ta for each wall
% Mn vs Ma for each wall 
% Mgbn vs Mgba
% Total nodal rotation: thetan(CASTEM) vs theta 

load mainvar

for h=1:3
    md=h;
f=figure;
p = uipanel('Parent',f,'Title','Total Shear Force on each wall','TitlePosition','centertop','FontSize',12,...
            'FontWeight','bold','FontName', 'Helvetica',...
               'BackgroundColor','white',...
               'BorderType','none'); 

for i=1:nw
subplot(round(nw/2),2,i,'Parent',p)
sForce_n(i)   = stairs(Tnum{md}(1:(end),i),x_t);
hold on
sForce_a(i)   = stairs(T{md}(1:(end),i),x_t);
hold on
sForce_cast(i)   = stairs(TCastem{md}(1:(end),i),x_t);
 

set(sForce_n(i)                         , ...
  'LineStyle'       , '--'        , ...
  'Color'           , 'r'         , ...
  'LineWidth'       , 1.5         );
set(sForce_a(i)                         , ...
   'Color'           , [0 0 .5]    , ...
  'LineWidth'       , 1.5         );
set(sForce_cast(i)       , ...
'LineStyle'       , '-.'        , ...
   'Color'           , [0 .5 0]    , ...
  'LineWidth'       , 1.5         );

hLegend = legend( ...
  [sForce_cast(i),sForce_n(i), sForce_a(i)], ...
  'Tn (CASTEM)' , ...
  'Tn (Un,\theta n)' , ...
  'Ta (Ua,\theta a)',...
  'location', 'NorthEast' );
nws=num2str(i);
nWall=strcat('Wall Axe: ',' ',nws);
hTitle  = title (nWall);
hXLabel = xlabel('Total Shear Force (KN)'                     );
hYLabel = ylabel('x (mm)'                      );
set([hTitle, hXLabel, hYLabel], ...
    'FontName'   , 'Times New Roman');
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 10          );
set( hTitle                    , ...
    'FontSize'   , 12          , ...
    'FontWeight' , 'bold'      );
set([hLegend, gca]             , ...
    'FontSize'   , 9           );
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , 0:lw:N*lw, ...
  'LineWidth'   , 1         );
end
set(gcf, 'Position', get(0, 'Screensize'));
end



for h=1:3
    md=h;
f=figure;
p = uipanel('Parent',f,'Title','Bending Moment on each wall','TitlePosition','centertop','FontSize',12,...
            'FontWeight','bold','FontName', 'Helvetica',...
               'BackgroundColor','white',...
               'BorderType','none'); 

for i=1:nw
subplot(round(nw/2),2,i,'Parent',p)
bMom_n(i)= line(Mnum{md}(:,i),x_t);
hold on
bMom_a(i)= line(M{md}(:,i), x_t);

set(bMom_n(i)                         , ...
  'LineStyle'       , '--'        , ...
  'Color'           , 'r'         , ...
  'LineWidth'       , 1.5         );
set(bMom_a(i)                         , ...
   'Color'           , [0 0 .5]    , ...
  'LineWidth'       , 1.5         );

hLegend = legend( ...
  [bMom_n(i), bMom_a(i)], ...
  'Mn (Un,\theta n)' , ...
  'Ma (Ua,\theta a)' , ...
  'location', 'NorthEast' );
nws=num2str(i);
nWall=strcat('Wall Axe: ',' ',nws);
hTitle  = title (nWall);
hXLabel = xlabel('Bending Moment (KNmm)'                     );
hYLabel = ylabel('x (mm)'                      );
set([hTitle, hXLabel, hYLabel], ...
    'FontName'   , 'Times New Roman');
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 10          );
set( hTitle                    , ...
    'FontSize'   , 12          , ...
    'FontWeight' , 'bold'      );
set([hLegend, gca]             , ...
    'FontSize'   , 9           );
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , 0:lw:N*lw, ...
  'LineWidth'   , 1         );
end
set(gcf, 'Position', get(0, 'Screensize'));
end


% 
% for h=1:3
%     md=h;
% f=figure;
% p = uipanel('Parent',f,'Title','Axial forces on external walls','TitlePosition','centertop','FontSize',12,...
%             'FontWeight','bold','FontName', 'Helvetica',...
%                'BackgroundColor','white',...
%                'BorderType','none'); 
% 
% i=1;
% subplot(round(nw/2),2,i,'Parent',p)
% bMom_n(i)= line(Mnum{md}(:,i),x_t);
% hold on
% bMom_a(i)= line(M{md}(:,i), x_t);
% 
% set(bMom_n(i)                         , ...
%   'LineStyle'       , '--'        , ...
%   'Color'           , 'r'         , ...
%   'LineWidth'       , 1.5         );
% set(bMom_a(i)                         , ...
%    'Color'           , [0 0 .5]    , ...
%   'LineWidth'       , 1.5         );
% 
% hLegend = legend( ...
%   [bMom_n(i), bMom_a(i)], ...
%   'Mn (Un,\theta n)' , ...
%   'Ma (Ua,\theta a)' , ...
%   'location', 'NorthEast' );
% nws=num2str(i);
% nWall=strcat('Wall Axe: ',' ',nws);
% hTitle  = title (nWall);
% hXLabel = xlabel('Bending Moment (KNmm)'                     );
% hYLabel = ylabel('x (mm)'                      );
% set([hTitle, hXLabel, hYLabel], ...
%     'FontName'   , 'Times New Roman');
% set([hXLabel, hYLabel]  , ...
%     'FontSize'   , 10          );
% set( hTitle                    , ...
%     'FontSize'   , 12          , ...
%     'FontWeight' , 'bold'      );
% set([hLegend, gca]             , ...
%     'FontSize'   , 9           );
% set( gca                       , ...
%     'FontName'   , 'Helvetica' );
% set(gca, ...
%   'Box'         , 'off'     , ...
%   'TickDir'     , 'out'     , ...
%   'TickLength'  , [.02 .02] , ...
%   'XMinorTick'  , 'on'      , ...
%   'YMinorTick'  , 'on'      , ...
%   'YGrid'       , 'on'      , ...
%   'XColor'      , [.3 .3 .3], ...
%   'YColor'      , [.3 .3 .3], ...
%   'YTick'       , 0:lw:N*lw, ...
%   'LineWidth'   , 1         );
% 
% set(gcf, 'Position', get(0, 'Screensize'));
% end
% 
% 
% 
% figs = findobj(0, 'type', 'figure'); 
% for k=1:length(figs)
%    set(gcf, 'PaperPositionMode', 'auto');
%     % print each figure in figs to a separate .eps file  
%     print(figs(k), '-djpeg', sprintf('IForces%d.jpg', k)) 
% end


end

